apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: mysecondapplication-java-quarkus-sample
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: mysecondapplication-java-quarkus-sample
    app.kubernetes.io/part-of: mysecondapplication
  name: mysecondapplication-java-quarkus-sample
  namespace: pshivpuj
spec:
  port:
    targetPort: 8081
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: mysecondapplication-java-quarkus-sample
    weight: 100
status: {}
