apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: mysecondapplication-java-quarkus-sample
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: mysecondapplication-java-quarkus-sample
    app.kubernetes.io/part-of: mysecondapplication
  name: mysecondapplication-java-quarkus-sample
  namespace: pshivpuj
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: mysecondapplication-java-quarkus-sample
status:
  loadBalancer: {}
