apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: mynewcomponent
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: mynewcomponent
    app.kubernetes.io/part-of: mysecondapplication
  name: mynewcomponent
  namespace: pshivpuj
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: mynewcomponent
    weight: 100
status: {}
