apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: mynewcomponent
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: mynewcomponent
    app.kubernetes.io/part-of: mysecondapplication
  name: mynewcomponent
  namespace: pshivpuj
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: mynewcomponent
status:
  loadBalancer: {}
